[package]
name = "b2m"
version = "0.11.1"
authors = ["snylonue <snylonue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde_json = "1.0"
failure = "0.1.5"

[profile.release]
lto = true